### PR TITLE
Dynamic form instance map

### PR DESCRIPTION
**Pull request by msn1992**
choose the second commit named (Map Marker added to the center geopoint)

### CODE REVIEW

**Comment by msn1992** [comment]
@hpardess I got a message that this branch has a conflict with the master branch, please resolve it

**Comment by hpardess** [comment]
I didn't get it... It has old code which is not required
```

<ng-container *ngSwitchCase="'geopoint'" >
		<input [formControlName]="question.key" [id]="question.key" [type]="question.type">
		<dynamic-list-instance-map></dynamic-list-instance-map>
	</ng-container>
```

As i remember it was removed and we has one component instead of this piece of code. Please meet me and we will decide to merge or discard.

**Comment by msn1992** [comment]
@hpardess this code is not showing for me and I checked it is unnecessary you can discard it.

**Comment by msn1992** [comment]
@hpardess  I can't see Forms options in the dashboard I have written the following code please check and marge it.

dynamic-form-question.component.html

<**geopoint-question** [form]="form" *ngSwitchCase="'geopoint'" [question]="question" [instanceId]="instanceId"></**geopoint-question**>





**geopoint-question.component.html**

<div [formGroup]="form" class="geopoint-container">
    <div class="map-container">
        <div class="map"  leaflet  [leafletOptions]="options"  ></div>
    </div>
    
    <label [attr.for]="question.key">{{question.label}}</label>
    <input [formControlName]="question.key" [type]="question.type">
</div>





**geopoint-question.component.ts** 

import { Component, Input, ViewChild, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { icon, latLng, marker, polyline, tileLayer } from 'leaflet';
import 'leaflet/dist/leaflet.css';

@Component({
  selector: 'geopoint-question',
	templateUrl: './geopoint-question.component.html',
	styleUrls: ['./geopoint-question.component.scss'],
})
export class GeopointQuestionComponent implements OnInit {
	@Input() question: any;
	@Input() instanceId: string;
	@Input() form: FormGroup;

	streetMaps = tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
		detectRetina: true, 
		attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
	});

	options = {
		layers: [ this.streetMaps],
		zoom: 8,
		center: latLng([ 34.499762, 69.158865 ])
	};

	constructor() {
		this.draw();
	}
	ngOnInit(){
		
	}

	draw(){
		let marker = this.getMarker(this.question.value);
		this.options.center = marker.getLatLng();
		this.options.layers.push(marker);
		console.log(this.options.center);
		console.log("geopoint question");
	}

	getMarker(geopoint) {
		let lat = this.getLatitude(this.question.value);
		let lon = this.getLongtitude(this.question.value);
		return marker([lat, lon], {
			icon: icon({
				iconSize: [ 25, 41 ],
				iconAnchor: [ 13, 41 ],
				iconUrl: 'https://npmcdn.com/leaflet@1.0.0-rc.3/dist/images/marker-icon.png',
			})
		});
	}
	  
	getLatitude(geopint) {
		return parseFloat(geopint.split(" ")[0]);
	}

	getLongtitude(geopint) {
		return parseFloat(geopint.split(" ")[1]);
	}
	
}

**Pull request closed without merging**
